### PR TITLE
Better xy

### LINKED ISSUE #551: XYPlot fails with 1 dimension
**Scenario:**
1. Create a node with at least 2 dimensions
2. Create XY-plot
2. Switch node back to one dimension

**Result:**
Resizing anything fails catastrophically.

**Proposed Solution:**
Shade out plot and change the label to "invalid dimensions", which informs the user of what is wrong, without making the decision to remove the plot for them.

I'm aiming for something that kind of looks like this, but feedback is appreciate on how to make this less visually harsh:
image

### PR DESCRIPTION
**Pull request by Seanny123**
Fixing a bunch of problems with XY plots:
- Direct mode is awkward for XY plots
- Axes don't cross at zero if you don't have uneven ranges on the x and y axis
- When you reduce dimensions from 2 to 1 and you have an xy-plot affected, bad things happen

Resolves #551 , #363 and #271

### CODE REVIEW

File: nengo_gui/static/components/2d_axes.js [hunk 1]
```diff
@@ -26,17 +24,15 @@ Nengo.Axes2D = function(parent, args) {
...
     /** spacing between the graph and the outside edges (in pixels) */
     this.set_axes_geometry(args.width, args.height);
-    
+
     /** define the x-axis */
     this.axis_x = d3.svg.axis()
         .scale(this.scale_x)
         .orient("bottom")
-        .ticks(2);
+        this.axis_x.ticks(2);
```
Comment (tcstewar) [inline nengo_gui/static/components/2d_axes.js]: why was this changed?

File: nengo_gui/static/components/2d_axes.js [hunk 2]
```diff
@@ -68,7 +64,7 @@ Nengo.Axes2D.prototype.set_axes_geometry = function(width, height) {
 /**
  * Adjust the graph layout due to changed size
  */
-Nengo.Axes2D.prototype.on_resize = function(width, height) {
+Nengo.Axes2D.prototype.on_resize = function(width, height, x_offset, y_offset) {
```
Comment (tcstewar) [inline nengo_gui/static/components/2d_axes.js]: Why pass in x_offset and y_offset and not use them?

File: nengo_gui/static/components/xyvalue.js [hunk 3]
```diff
@@ -73,20 +79,62 @@ Nengo.XYValue.prototype.on_message = function(event) {
...
-        .x(function(d, i) {
-            return self.axes2d.scale_x(
-                shown_data[self.index_x][i]);
-            })
-        .y(function(d) {return self.axes2d.scale_y(d);})
-    this.path.data([shown_data[this.index_y]])
-             .attr('d', line);
+    /** update the lines if there is data with valid dimensions */
+    var good_idx = self.index_x < self.n_lines && self.index_y < self.n_lines
+    if (this.data_store.data.length > 1 && good_idx) {
```
Comment (tcstewar) [inline nengo_gui/static/components/xyvalue.js]: This should just be ```if(good_idx)``` (so you can plot 0,0 on a 1-D, if you want to)

**Comment by tcstewar** [comment]
The white box in the background when the error message is there gets a bit odd when the window is resized.  Perhaps get rid of the background white box and just mark the text as having background and a border in HTML?

**Comment by tcstewar** [comment]
Circle should be 50% opacity, and @jgosmann thinks it should be blue.  (I concur, but really shouldn't have a vote).

File: nengo_gui/static/components/xyvalue.js [hunk 4]
```diff
@@ -73,20 +79,62 @@ Nengo.XYValue.prototype.on_message = function(event) {
...
+          .attr("fill", "white")
+          .attr("stroke-width", 1)
+          .attr("stroke", "rgb(0,0,0)")
+          .attr("fill-opacity", 1);
+
+        // create the HTML text element
+        this.warning_text = document.createElement('div');
+        this.div.appendChild(this.warning_text);
+        this.warning_text.innerHTML = "Change<br>Dimension<br>Indices";
+        this.warning_text.style = "color:#a94442; position: absolute; text-align: center; margin-left: auto; margin-right: auto; width:100%; top:37%; display:box; box-align:center; box-pack:center;"
```
Comment (tcstewar) [inline nengo_gui/static/components/xyvalue.js]: This should be in the style sheet

**Comment by tcstewar** [comment]
Looks good to me!
